export const formArray = {
  firstName: {
    type: "text",
    name: "first_name",
    id: "first-name",
    color: "primary",
    label: "First Name",
    isRequired: true,
    variant: "bordered",
    isClearable: true,
    radius: "lg",
  },
  lastName: {
    type: "text",
    name: "last_name",
    id: "last-name",
    label: "Last Name",
    color: "primary",
    isRequired: true,
    variant: "bordered",
    isClearable: true,
    radius: "lg",
  },
  email: {
    type: "email",
    name: "email",
    id: "email",
    label: "Email",
    color: "primary",
    isRequired: true,
    variant: "bordered",
    isClearable: true,
    radius: "lg",
  },
  message: {
    type: "textarea",
    name: "message",
    id: "message",
    labelPlacement: "outside",
    placeholder: "Enter your message",
    variant: "bordered",
    label: "Message",
    color: "primary",
    isRequired: true,
  },
};
